server:
  port: 8082

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/VaccinationCenterDB
    password: root
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect

  application:
    name: VACCINATION-CENTER-SERVICE


resilience4j.retry:
  instances:
    citizen-api:
      maxAttempts: 6
      waitDuration: 10s
      enableExponentialBackoff: true
      exponentialBackoffMultiplier: 2